-- Interested posts and upcoming events tables + policies + trigger helpers

-- 1) Tables (id identity, post_id references)
create table if not exists public.user_interested_posts (
  id bigint generated by default as identity not null,
  post_id uuid null default gen_random_uuid(),
  user_id uuid null,
  constraint user_interested_posts_pkey primary key (id),
  constraint user_interested_posts_post_id_fkey foreign key (post_id) references public.all_posts (post_id) on update cascade on delete cascade,
  constraint user_interested_posts_user_id_fkey foreign key (user_id) references public.user_info (auth_uid)
) tablespace pg_default;

create table if not exists public.user_upcoming_events (
  upcoming_event_id bigint generated by default as identity not null,
  post_id uuid not null default gen_random_uuid(),
  user_id uuid null,
  constraint user_upcoming_events_pkey primary key (upcoming_event_id),
  constraint user_upcoming_events_post_id_fkey foreign key (post_id) references public.event_posts (post_id) on update cascade on delete cascade,
  constraint user_upcoming_events_user_id_fkey foreign key (user_id) references public.user_info (auth_uid) on update cascade on delete cascade
) tablespace pg_default;

-- 2) De-duplication
create unique index if not exists user_interested_posts_user_post_uniq
  on public.user_interested_posts (user_id, post_id);

create unique index if not exists user_upcoming_events_user_post_uniq
  on public.user_upcoming_events (user_id, post_id);

-- 3) Row Level Security
alter table public.user_interested_posts enable row level security;
alter table public.user_upcoming_events enable row level security;

-- Interested posts: user can manage their own rows
create policy if not exists "select own interested posts"
  on public.user_interested_posts
  for select
  using (auth.uid() = user_id);

create policy if not exists "insert own interested posts"
  on public.user_interested_posts
  for insert
  with check (auth.uid() = user_id);

create policy if not exists "delete own interested posts"
  on public.user_interested_posts
  for delete
  using (auth.uid() = user_id);

-- Upcoming events: user can read their own rows
create policy if not exists "select own upcoming events"
  on public.user_upcoming_events
  for select
  using (auth.uid() = user_id);

-- Allow users to remove upcoming rows (optional cleanup)
create policy if not exists "delete own upcoming events"
  on public.user_upcoming_events
  for delete
  using (auth.uid() = user_id);

-- 4) Trigger helpers

-- Insert into upcoming when an interested EVENT starts within 7 days.
create or replace function public._handle_user_interest_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  ev_start date;
  is_event boolean;
begin
  if new.user_id is null or new.post_id is null then
    return new;
  end if;

  select (type = 'event') into is_event
  from public.all_posts
  where post_id = new.post_id;

  if not coalesce(is_event, false) then
    return new;
  end if;

  select event_start_date::date into ev_start
  from public.event_posts
  where post_id = new.post_id;

  if ev_start is null then
    return new;
  end if;

  if ev_start >= current_date and ev_start < (current_date + interval '7 days') then
    insert into public.user_upcoming_events (post_id, user_id)
    values (new.post_id, new.user_id)
    on conflict (user_id, post_id) do nothing;
  end if;

  return new;
end;
$$;

create or replace function public._handle_user_interest_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.user_id is null or old.post_id is null then
    return old;
  end if;

  delete from public.user_upcoming_events
  where user_id = old.user_id and post_id = old.post_id;

  return old;
end;
$$;

-- When an event's start date changes, recompute upcoming entries for interested users.
create or replace function public._handle_event_date_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  ev_start date;
begin
  ev_start := new.event_start_date::date;

  delete from public.user_upcoming_events where post_id = new.post_id;

  if ev_start is not null and ev_start >= current_date and ev_start < (current_date + interval '7 days') then
    insert into public.user_upcoming_events (post_id, user_id)
    select new.post_id, uip.user_id
    from public.user_interested_posts uip
    where uip.post_id = new.post_id and uip.user_id is not null
    on conflict (user_id, post_id) do nothing;
  end if;

  return new;
end;
$$;

-- 5) Triggers

drop trigger if exists trg_user_interest_insert on public.user_interested_posts;
create trigger trg_user_interest_insert
after insert on public.user_interested_posts
for each row
execute function public._handle_user_interest_insert();

drop trigger if exists trg_user_interest_delete on public.user_interested_posts;
create trigger trg_user_interest_delete
after delete on public.user_interested_posts
for each row
execute function public._handle_user_interest_delete();

drop trigger if exists trg_event_date_update on public.event_posts;
create trigger trg_event_date_update
after update of event_start_date on public.event_posts
for each row
execute function public._handle_event_date_update();

-- NOTE:
-- Triggers can only run on writes (insert/update/delete). They cannot do periodic checks by themselves.
-- For periodic syncing (e.g. users mark interest weeks earlier), use a scheduled job
-- (Supabase Scheduled Edge Function or pg_cron if enabled) to run a refresh routine.
